apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-mycavanaughnetwork-cert-staging
  namespace: traefik-system
spec:
  commonName: traefik.mycavanaughnetwork.com
  secretName: traefik-mycavanaughnetwork-cert-staging
  dnsNames:
    - traefik.mycavanaughnetwork.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
