---
# Traefik Secrets
apiVersion: v1
kind: Secret
metadata:
  name: route53-traefik-secret
  namespace: cert-manager
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: AKIAVNTS7S...
  AWS_SECRET_ACCESS_KEY: dVOqf8In9mj+....
  AWS_REGION: us-east-2
  AWS_HOSTED_ZONE_ID: Z006387....
