---
# dnsHostPort:
#   enabled: true
#   port: 53
serviceDns:
  type: LoadBalancer
  loadBalancerIP: "192.168.1.210"
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
serviceDhcp:
  type: LoadBalancer
  loadBalancerIP: "192.168.1.210"
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
serviceWeb:
  type: LoadBalancer
  loadBalancerIP: "192.168.1.210"
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
persistentVolumeClaim:
  enabled: true
  existingClaim: "pihole"
  annotations: {}
  accessModes:
    - ReadWriteOnce
  size: "500Mi"
admin:
  existingSecret: "pihole-secret"
# webHttp: "55480"
# webHttps: "55443"
hostNetwork: "true"
privileged: "true"
DNS1: "8.8.8.8"
DNS2: "8.8.4.4"
# podDnsConfig:
#   enabled: true
#   policy: "None"
#   nameservers:
#   - 127.0.0.1
#   - 8.8.8.8
extraEnvVars:
  TZ: "America/Detroit"
  # ServerIP: 192.168.1.23 ## This is the node in the cluster that it will always load on
