## pihole-values.yaml---
replicaCount: 1
strategyType: RollingUpdate
maxSurge: 1
maxUnavailable: 1
image:
  repository: "pihole/pihole"
  tag: v5.8.1
  pullPolicy: IfNotPresent
dnsHostPort:
  enabled: true
  port: 53
serviceDns:
  mixedService: false
  type: NodePort
  port: 53
  externalTrafficPolicy: Local
  loadBalancerIP: ""
  annotations: {}
    # metallb.universe.tf/address-pool: network-services
    # metallb.universe.tf/allow-shared-ip: pihole-svc
serviceDhcp:
  enabled: true
  type: NodePort
  externalTrafficPolicy: Local
  loadBalancerIP: ""
  annotations: {}
    # metallb.universe.tf/address-pool: network-services
    # metallb.universe.tf/allow-shared-ip: pihole-svc
serviceWeb:
  http:
    enabled: true
    port: 80
  https:
    enabled: true
    port: 443
  type: ClusterIP
  externalTrafficPolicy: Local
  loadBalancerIP: ""
  annotations: {}
    # metallb.universe.tf/address-pool: network-services
    # metallb.universe.tf/allow-shared-ip: pihole-svc
virtualHost: pi.hole
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 60
    failureThreshold: 10
    timeoutSeconds: 5
  readiness:
    enabled: true
    initialDelaySeconds: 60
    failureThreshold: 3
    timeoutSeconds: 5
persistentVolumeClaim:
  enabled: true
  existingClaim: "pihole"
  annotations: {}
  accessModes:
    - ReadWriteOnce
  size: "500Mi"
serviceTCP:
  type: ClusterIP
serviceUDP:
  type: ClusterIP
admin:
  existingSecret: "pihole-secret"
antiaff:
  enabled: false
  avoidRelease: pihole1
  strict: true
webHttp: "55480"
webHttps: "55443"
hostNetwork: "true"
privileged: "true"
podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
  - 127.0.0.1
  - 8.8.8.8
extraEnvVars:
  TZ: "America/Detroit"
  ServerIP: 192.168.1.23 ## This is the primary control place kubernetes cluster
